name: Black Formatter

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Lint (isort/black)
        uses: wrboyce/python-lint-action@v1.0.0